export type TemplateNote = { blockKey: string; text: string; color: string }
export type ProjectTemplate = { id: string; name: string; description: string; notes: TemplateNote[] }

export const projectTemplates: ProjectTemplate[] = [
  {
    id: 'pmo-platform',
    name: 'Implantação de plataforma de PMO',
    description: 'Canvas de um projeto real de criação de um workspace colaborativo de PMO. Bom ponto de partida para projetos internos de ferramentas e processos.',
    notes: [
      { blockKey: 'why', text: 'Reduzir o tempo de planejamento em 50%.', color: 'mint' },
      { blockKey: 'why', text: 'Criar uma linguagem comum entre áreas e patrocinadores.', color: 'yellow' },
      { blockKey: 'objectives', text: 'Ter 80% dos projetos estratégicos validados pela equipe até dezembro.', color: 'lavender' },
      { blockKey: 'objectives', text: 'Dar visibilidade às decisões em uma única página.', color: 'peach' },
      { blockKey: 'benefits', text: 'Alinhamento rápido entre quem decide e quem executa.', color: 'mint' },
      { blockKey: 'benefits', text: 'Menos retrabalho durante a execução.', color: 'yellow' },
      { blockKey: 'product', text: 'Workspace colaborativo para criar, revisar e publicar canvases.', color: 'blue' },
      { blockKey: 'requirements', text: 'Edição por cartões, comentários, versões e exportação em PDF.', color: 'peach' },
      { blockKey: 'requirements', text: 'Acesso seguro por organização e por projeto.', color: 'mint' },
      { blockKey: 'stakeholders', text: 'Diretoria e patrocinadores do portfólio.', color: 'lavender' },
      { blockKey: 'stakeholders', text: 'Áreas parceiras e clientes convidados.', color: 'yellow' },
      { blockKey: 'team', text: 'PMO, gerentes de projeto, produto e especialistas.', color: 'blue' },
      { blockKey: 'assumptions', text: 'A organização já utiliza e-mail corporativo.', color: 'mint' },
      { blockKey: 'assumptions', text: 'As decisões devem ser revisadas mensalmente.', color: 'peach' },
      { blockKey: 'deliverables', text: 'MVP web, templates, governança e trilha de auditoria.', color: 'yellow' },
      { blockKey: 'constraints', text: 'Primeira versão deve funcionar sem treinamento formal.', color: 'lavender' },
      { blockKey: 'risks', text: 'Baixa adesão de áreas acostumadas a planilhas.', color: 'peach' },
      { blockKey: 'risks', text: 'Escopo crescer antes da validação do MVP.', color: 'coral' },
      { blockKey: 'timeline', text: 'Descoberta: 2 semanas · MVP: 12 semanas · Piloto: 4 semanas.', color: 'blue' },
      { blockKey: 'costs', text: 'Orçamento inicial reservado para produto e infraestrutura.', color: 'mint' },
    ],
  },
  {
    id: 'digital-product-launch',
    name: 'Lançamento de produto digital',
    description: 'Canvas para lançar um app ou funcionalidade nova, do MVP ao go-live. Bom ponto de partida para projetos de produto e tecnologia.',
    notes: [
      { blockKey: 'why', text: 'Aumentar a retenção de usuários em 15% no primeiro trimestre.', color: 'mint' },
      { blockKey: 'why', text: 'Responder à demanda recorrente de clientes por notificações em tempo real.', color: 'yellow' },
      { blockKey: 'objectives', text: 'Lançar a funcionalidade para 100% da base até o fim do trimestre.', color: 'lavender' },
      { blockKey: 'objectives', text: 'Manter a taxa de erro abaixo de 0,5% nas duas primeiras semanas.', color: 'peach' },
      { blockKey: 'benefits', text: 'Reduz o tempo de resposta do suporte em tickets recorrentes.', color: 'mint' },
      { blockKey: 'benefits', text: 'Diferencia o produto frente aos concorrentes diretos.', color: 'yellow' },
      { blockKey: 'product', text: 'Sistema de notificações push e in-app configurável pelo usuário.', color: 'blue' },
      { blockKey: 'requirements', text: 'Funcionar em iOS, Android e web sem app nativo adicional.', color: 'peach' },
      { blockKey: 'requirements', text: 'Permitir opt-out granular por tipo de notificação.', color: 'mint' },
      { blockKey: 'stakeholders', text: 'Clientes-piloto do programa de early access.', color: 'lavender' },
      { blockKey: 'stakeholders', text: 'Time de suporte, que vai lidar com as primeiras dúvidas.', color: 'yellow' },
      { blockKey: 'team', text: 'Squad de produto, dois desenvolvedores mobile e um QA dedicado.', color: 'blue' },
      { blockKey: 'assumptions', text: 'A infraestrutura de push já existe e está estável.', color: 'mint' },
      { blockKey: 'assumptions', text: 'Usuários já aceitaram receber notificações (opt-in configurado).', color: 'peach' },
      { blockKey: 'deliverables', text: 'Feature flag, documentação de suporte, campanha de comunicação in-app.', color: 'yellow' },
      { blockKey: 'constraints', text: 'Não pode aumentar o consumo de bateria em mais de 2%.', color: 'lavender' },
      { blockKey: 'risks', text: 'Provedores de push (APNs/FCM) terem instabilidade no período de lançamento.', color: 'peach' },
      { blockKey: 'risks', text: 'Volume de notificações gerar fadiga e aumento de opt-out.', color: 'coral' },
      { blockKey: 'timeline', text: 'Beta fechado: 3 semanas · Beta aberto: 2 semanas · Lançamento geral: 1 semana.', color: 'blue' },
      { blockKey: 'costs', text: 'Custo adicional de infraestrutura de push dentro do orçamento já aprovado.', color: 'mint' },
    ],
  },
  {
    id: 'corporate-event',
    name: 'Evento corporativo',
    description: 'Canvas para organizar um evento presencial ou híbrido, da definição do público à logística do dia. Bom ponto de partida para marketing e eventos.',
    notes: [
      { blockKey: 'why', text: 'Fortalecer o relacionamento com os principais clientes da carteira.', color: 'mint' },
      { blockKey: 'why', text: 'Apresentar o roadmap do produto para o mercado.', color: 'yellow' },
      { blockKey: 'objectives', text: 'Reunir pelo menos 150 participantes confirmados.', color: 'lavender' },
      { blockKey: 'objectives', text: 'Atingir nota média 4,5/5 na pesquisa de satisfação pós-evento.', color: 'peach' },
      { blockKey: 'benefits', text: 'Gera leads qualificados para o time comercial.', color: 'mint' },
      { blockKey: 'benefits', text: 'Fortalece a marca empregadora entre candidatos presentes.', color: 'yellow' },
      { blockKey: 'product', text: 'Evento híbrido de um dia, com palestras, mesas-redondas e networking.', color: 'blue' },
      { blockKey: 'requirements', text: 'Transmissão ao vivo estável para o público remoto.', color: 'peach' },
      { blockKey: 'requirements', text: 'Espaço físico com capacidade para 200 pessoas.', color: 'mint' },
      { blockKey: 'stakeholders', text: 'Clientes e parceiros convidados.', color: 'lavender' },
      { blockKey: 'stakeholders', text: 'Imprensa e influenciadores do setor.', color: 'yellow' },
      { blockKey: 'team', text: 'Marketing de eventos, comercial, TI de suporte e recepção.', color: 'blue' },
      { blockKey: 'assumptions', text: 'O local reservado estará disponível na data confirmada.', color: 'mint' },
      { blockKey: 'assumptions', text: 'Palestrantes convidados confirmam presença com um mês de antecedência.', color: 'peach' },
      { blockKey: 'deliverables', text: 'Programação final, materiais de apoio, gravação das sessões.', color: 'yellow' },
      { blockKey: 'constraints', text: 'Orçamento total não pode ultrapassar o valor aprovado pelo comitê.', color: 'lavender' },
      { blockKey: 'risks', text: 'Cancelamento de palestrante-chave em cima da hora.', color: 'peach' },
      { blockKey: 'risks', text: 'Baixa adesão do público remoto na transmissão.', color: 'coral' },
      { blockKey: 'timeline', text: 'Planejamento: 6 semanas · Divulgação: 4 semanas · Evento: 1 dia · Pós-evento: 1 semana.', color: 'blue' },
      { blockKey: 'costs', text: 'Inclui locação de espaço, catering, transmissão e brindes.', color: 'mint' },
    ],
  },
]
